export const PSYCHOLOGY_CONSTANTS = {
  WORDS_PER_MINUTE: 145,
  OPTIMAL_HOOK_MAX_SECONDS: 8,
  CAUTION_HOOK_MAX_SECONDS: 12,
  LOSS_AVERSION_KEYWORDS: [
    "mistake",
    "stop",
    "never",
    "nobody",
    "worst",
    "ruining",
    "waste",
    "trap",
    "warning",
    "avoid",
    "failing",
    "dying",
    "scam",
  ],
  CURIOSITY_KEYWORDS: [
    "why",
    "this",
    "secret",
    "truth",
    "hidden",
    "revealed",
    "real reason",
    "nobody talks about",
    "actually",
  ],
  EXTREME_STAKES_PATTERNS: [
    /\$\d+/i,
    /\d+x/i,
    /\d+%/i,
    /\b(zero|0)\b.*\b(hero|100|million)\b/i,
    /\b(first|last|only)\b/i,
  ],
} as const;
