export const API_ROUTES = {
  PROJECTS: "/api/projects",
  INSPIRATIONS: "/api/inspirations",
  INSPIRATION_TAG: "/api/inspirations/tag",
  ASSETS: "/api/assets",
  YOUTUBE: "/api/youtube",
  YOUTUBE_CHANNEL: "/api/youtube/channel",
  MEDIA: "/api/media",
  MEDIA_UPLOAD: "/api/media/upload",
  SETTINGS: "/api/settings",
  ANALYZE_HOOK: "/api/analyze-hook",
  CHANNELS: "/api/channels",
  CHANNELS_DETAIL: (id: string) => `/api/channels/${id}`,
  COMPETITORS: "/api/competitors",
  COMPETITORS_DETAIL: (id: string) => `/api/competitors/${id}`,
  THUMBNAIL_PROMPT: "/api/thumbnail-prompt",
  FORGOT_PASSWORD: "/api/auth/forgot-password",
  RESET_PASSWORD: "/api/auth/reset-password",
} as const;
